-- +goose Up

-- Every room at the inn requires stairs, including the two the owner considers
-- most accessible. With the accessibility filter switched off there is nothing
-- on the site that says so, and a guest with mobility needs would find out on
-- arrival. This is owner-editable copy rather than hardcoded text so it can be
-- corrected without a deploy.
ALTER TABLE settings ADD COLUMN accessibility_notice text NOT NULL DEFAULT
  'Beal House is a historic home and every room requires the use of stairs. '
  'Please contact us before booking if you have mobility needs, and we will '
  'help you find the best-suited room.';

CREATE TABLE room_photos (
  id         bigserial PRIMARY KEY,
  room_id    bigint NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  -- Path on the VPS disk. The AVIF/WebP variants generated by the image
  -- pipeline are derived from this, so only the original is stored.
  path       text NOT NULL,
  -- Required, not nullable: a photo with no alt text is unusable to a screen
  -- reader and the admin uploader should refuse to save without it.
  alt_text   text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX room_photos_room_id_sort_idx ON room_photos (room_id, sort_order);

-- +goose Down
DROP TABLE room_photos;
ALTER TABLE settings DROP COLUMN accessibility_notice;
