package booking

import (
	"crypto/rand"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5/pgconn"
)

// The statuses a booking can hold, matching the CHECK constraint on the column.
// Step 3 only ever writes StatusPending; payment, cancellation and expiry
// arrive with steps 4 and 5.
const (
	StatusPending   = "pending"
	StatusConfirmed = "confirmed"
	StatusCancelled = "cancelled"
	StatusExpired   = "expired"
)

// codeAlphabet omits I, O, 0 and 1. A guest reads this code out over the phone
// to an owner writing it down, and those four are where that goes wrong.
//
// Its length divides 256 exactly, so mapping a random byte into it is uniform
// with no modulo bias and no rejection loop.
const codeAlphabet = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ"

// codeLength of 6 over a 32-character alphabet is about a billion codes. Long
// enough that collisions are a curiosity rather than a design problem, short
// enough to say out loud.
const codeLength = 6

// codePrefix makes a code recognisable in an inbox or a search field.
const codePrefix = "BH-"

// codeAttempts bounds the collision retry. Two failures in a row means
// something other than chance is wrong.
const codeAttempts = 3

func newCode() (string, error) {
	buf := make([]byte, codeLength)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("booking: generating a code: %w", err)
	}
	for i, b := range buf {
		buf[i] = codeAlphabet[int(b)%len(codeAlphabet)]
	}
	return codePrefix + string(buf), nil
}

// isDuplicateCode reports a unique-violation, which for this insert can only be
// the code: everything else the statement writes is either generated by the
// database or a foreign key.
func isDuplicateCode(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23505"
}
